spring:
  main:
    banner-mode: "off"
  application:
    name: rabbitmq-application
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                deliveryMode: ${DELIVERY_MODE:2}
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: ${RABBIT_VHOST:/}
      bindings:
        developer_routing:
          destination: queue.developers_exchange
          binder: rabbit
          group: developer_queue

#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/testdb
#    username: root
#    password: root
#  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      schema-locations: classpath:data/table.sql
#      data-locations: classpath:data/data.sql
#      enabled: true
#token:
#    secret: shipul
#    validity: 100500
#    header: auth
feign:
  client:
    config:
      developer:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        requestInterceptors:
#          - by.shipul.stepic.feign.interceptor.DeveloperFeignClientInterceptor


