
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: root
    password: root
  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      schema-locations: classpath:data/table.sql
#      data-locations: classpath:data/data.sql
#      enabled: true
#token:
#    secret: shipul
#    validity: 100500
#    header: auth
feign:
  client:
    config:
      developer:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        requestInterceptors:
#          - by.shipul.stepic.feign.interceptor.DeveloperFeignClientInterceptor

